# Generated by Django 2.1.2 on 2018-11-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('run', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=2)),
                ('abuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuelo.Abuelo')),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuelo.Alarma')),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('horaInicio', models.IntegerField()),
                ('cantVeces', models.IntegerField()),
                ('abuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuelo.Abuelo')),
            ],
        ),
        migrations.AddField(
            model_name='alarma',
            name='remedio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuelo.Remedio'),
        ),
        migrations.AddField(
            model_name='abuelo',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuelo.Cuidador'),
        ),
    ]
